version: '3'

services:
  # asai-app:
  #   container_name: asai-app
  #   build:
  #     context: ./asai-app-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8082:8082"
  #   volumes:
  #     - ./asai-app-service:/app
  #   depends_on:
  #     - asai-db
  #   #   - asai-engine
  #   networks:
  #     - asai-network
  
  asai-engine:
    container_name: asai-engine
    environment:
      - ENVIRONMENT=LOCAL DEV
    build:
      context: ./asai-engine-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./asai-engine-service:/app
    depends_on:
      - asai-db
    networks:
      - asai-network

  asai-db:
    image: postgres:9.6.12
    container_name: asai-db
    environment:
      - POSTGRES_DB=asai-db
      - POSTGRES_USER=asai-admin
      - POSTGRES_PASSWORD=asai-password
      - DATABASE_PORT=5432
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - asai-network

volumes:
  db-data:

networks:
  asai-network: