# - owner:
#   user_id:
#   name:
# - avatar:
#   id: 
#   name:
#   model:
#   primer: 
#   public:
#   temperment:
#   agents:
#   - agent_id:
#     name:
#     model:
#     defulat_primer: 
#     primer:
#     active:
#     public:
#     tools: 
#     - tool_id:
#       name:
#       token:  
#   plugins:
#   - plugin_id:
#     name:
#     token:
#   tools:
#   - tool_id:
#     name:
#     token: 


