version: '3'

services: 
  asai-app:
    environment:
      - ENVIRONMENT=LOCAL DEV
      - CGO_CFLAGS=-D_LARGEFILE64_SOURCE

  asai-db:
    ports:
      - 8082:8082
    environment:
      - POSTGRES_DB=asai-db
      - POSTGRES_USER=asai-admin
      - POSTGRES_PASSWORD=asai-password
      - DATABASE_PORT=5432
